(**** Beginning of end.gcode ****)
(**** begin move to cooling position ****)
G1 X0.0 Y55.0 F3300.0 (move to cooling position)
(**** end move to cooling position ****)
(**** begin filament reversal ****)
M108 R1.98 (set extruder speed)
M102 (Extruder on, reverse)
G04 P2000 (Wait t/1000 seconds)
M103 (Extruder off)
(**** end filament reversal ****)
M18 (Turn off steppers)
(**** begin cool for safety ****)
M104 S0 (set extruder temperature)
M109 S0 (set heated-build-platform temperature)
(**** end cool for safety ****)
(**** end of end.gcode ****)
