/*
 Part of the ReplicatorG project - http://www.replicat.org
 Copyright (c) 2008 Zach Smith

 Forked from Arduino: http://www.arduino.cc

 Based on Processing http://www.processing.org
 Copyright (c) 2004-05 Ben Fry and Casey Reas
 Copyright (c) 2001-04 Massachusetts Institute of Technology

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 $Id: MainWindow.java 370 2008-01-19 16:37:19Z mellis $
 */

package replicatorg.app.ui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DecimalFormat;
import java.util.EnumSet;
import java.util.Enumeration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.vecmath.Point3d;

import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import replicatorg.app.Base;
import replicatorg.app.MachineController;
import replicatorg.app.tools.XML;
import replicatorg.drivers.Driver;
import replicatorg.machine.MachineListener;
import replicatorg.machine.MachineProgressEvent;
import replicatorg.machine.MachineStateChangeEvent;
import replicatorg.machine.MachineToolStatusEvent;
import replicatorg.machine.model.Axis;
import replicatorg.machine.model.ToolModel;

public class ControlPanelWindow extends JFrame implements ActionListener,
		ChangeListener, ItemListener, FocusListener, WindowListener,
		MachineListener {
	// Autogenerated by serialver
	static final long serialVersionUID = -3494348039028986935L;

	protected JPanel mainPanel;

	protected JPanel jogPanel;

	protected JButton xPlusButton;
	protected JButton xMinusButton;
	protected JButton yPlusButton;
	protected JButton yMinusButton;
	protected JButton zPlusButton;
	protected JButton zMinusButton;

	protected JButton zeroButton;

	protected JPanel extruderPanel;

	protected double jogRate;

	protected Pattern jogPattern;

	protected String[] jogStrings = { "0.01mm", "0.05mm", "0.1mm", "0.5mm",
			"1mm", "5mm", "10mm", "20mm", "50mm" };

	protected JSlider xyFeedrateSlider;
	protected JTextField xyFeedrateValue;

	protected JSlider zFeedrateSlider;
	protected JTextField zFeedrateValue;

	protected JTextField xPosField;
	protected JTextField yPosField;
	protected JTextField zPosField;

	protected JTextField currentTempField;
	
	protected JTextField platformCurrentTempField;

	protected JTabbedPane toolsPane;

	protected MachineController machine;

	protected Driver driver;

	protected UpdateThread updateThread;

	protected PollThread pollThread;
	
	private static ControlPanelWindow instance = null;

	public static synchronized ControlPanelWindow getControlPanel(MachineController m) {
		if (instance == null) {
			instance = new ControlPanelWindow(m);
		} else {
			if (instance.machine != m) {
				instance.dispose();
				instance = new ControlPanelWindow(m);
			}
		}
		return instance;
	}
	
	private ControlPanelWindow(MachineController m) {
		super("Control Panel");

		// save our machine!
		machine = m;
		driver = machine.getDriver();
		driver.invalidatePosition(); // Always force a query when we open the panel

		// Listen to it-- stop and close if we're in build mode.
		machine.addMachineStateListener(this);
		
		// make it a reasonable size
		// Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		// int myWidth = screen.width-40;
		// int myHeight = screen.height-40;
		int myWidth = 450;
		int myHeight = 700;

		// compile our regexes
		jogRate = 10.0;
		jogPattern = Pattern.compile("([.0-9]+)");
		// jogStrings = ;

		setBounds(40, 40, myWidth, myHeight);

		// default behavior
		setDefaultCloseOperation(DISPOSE_ON_CLOSE);

		// no resizing... yet
		setResizable(false);

		// no menu bar.
		setJMenuBar(createMenuBar());

		// create all our GUI interfaces
		mainPanel = new JPanel();
		BoxLayout bl = new BoxLayout(mainPanel, BoxLayout.PAGE_AXIS);
		mainPanel.setLayout(bl);
		createJogPanel();
		mainPanel.add(Box.createRigidArea(new Dimension(0, 10)));
		createActivationPanel();
		mainPanel.add(Box.createRigidArea(new Dimension(0, 10)));
		// mainPanel.add(Box.createVerticalGlue());
		createToolsPanel();
		add(mainPanel);

		// add our listener hooks.
		addWindowListener(this);
		// addWindowFocusListener(this);
		// addWindowStateListener(this);

		// start our various threads.
		updateThread = new UpdateThread(this);
		updateThread.start();
		pollThread = new PollThread(driver);
		pollThread.start();
	}

	private JMenuItem makeHomeItem(String name,final EnumSet<Axis> set,final boolean positive) {
		JMenuItem item = new JMenuItem(name);
		item.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				driver.homeAxes(set,positive);
			}
		});
		return item;
	}

	protected JMenuBar createMenuBar() {
		JMenuBar bar = new JMenuBar();
		JMenu homeMenu = new JMenu("Homing");
		bar.add(homeMenu);
		homeMenu.add(makeHomeItem("Home X+",EnumSet.of(Axis.X),true));
		homeMenu.add(makeHomeItem("Home X-",EnumSet.of(Axis.X),false));
		homeMenu.add(makeHomeItem("Home Y+",EnumSet.of(Axis.Y),true));
		homeMenu.add(makeHomeItem("Home Y-",EnumSet.of(Axis.Y),false));
		homeMenu.add(makeHomeItem("Home Z+",EnumSet.of(Axis.Z),true));
		homeMenu.add(makeHomeItem("Home Z-",EnumSet.of(Axis.Z),false));
		homeMenu.add(new JSeparator());
		homeMenu.add(makeHomeItem("Home XY+",EnumSet.of(Axis.X,Axis.Y),true));
		homeMenu.add(makeHomeItem("Home XY-",EnumSet.of(Axis.X,Axis.Y),false));
		homeMenu.add(makeHomeItem("Home all+",EnumSet.allOf(Axis.class),true));
		homeMenu.add(makeHomeItem("Home all-",EnumSet.allOf(Axis.class),false));
		return bar;
	}

	protected JButton createJogButton(String text, String tooltip) {
		final int buttonSize = 60;
		JButton b = new JButton(text);
		b.setToolTipText(tooltip);
		b.setMaximumSize(new Dimension(buttonSize, buttonSize));
		b.setPreferredSize(new Dimension(buttonSize, buttonSize));
		b.setMinimumSize(new Dimension(buttonSize, buttonSize));
		b.addActionListener(this);
		return b;
	}

	protected JTextField createDisplayField() {
		int textBoxWidth = 160;

		JTextField tf = new JTextField();
		tf.setMaximumSize(new Dimension(textBoxWidth, 25));
		tf.setMinimumSize(new Dimension(textBoxWidth, 25));
		tf.setPreferredSize(new Dimension(textBoxWidth, 25));
		tf.setEnabled(false);
		return tf;
	}

	protected void createJogPanel() {
		// how big you want 'em boss?
		int textBoxWidth = 160;

		xPlusButton = createJogButton("X+", "Jog X axis in positive direction");
		xMinusButton = createJogButton("X-", "Jog X axis in negative direction");
		yPlusButton = createJogButton("Y+", "Jog Y axis in positive direction");
		yMinusButton = createJogButton("Y-", "Jog Y axis in negative direction");
		zPlusButton = createJogButton("Z+", "Jog Z axis in positive direction");
		zMinusButton = createJogButton("Z-", "Jog Z axis in negative direction");
		zeroButton = createJogButton("<html>Set<br/>zero",
				"Mark Current Position as Zero (0,0,0)");
		zeroButton.setActionCommand("Zero");
		// xPlusButton.setMnemonic(KeyEvent.VK_KP_RIGHT);
		// xMinusButton.setMnemonic(KeyEvent.VK_KP_LEFT);
		// yPlusButton.setMnemonic(KeyEvent.VK_KP_UP);
		// yMinusButton.setMnemonic(KeyEvent.VK_KP_DOWN);
		// zPlusButton.setMnemonic(KeyEvent.VK_PLUS);
		// zMinusButton.setMnemonic(KeyEvent.VK_MINUS);
		// zero.setMnemonic(KeyEvent.VK_ZERO);

		// create our position panel
		JPanel positionPanel = new JPanel();
		positionPanel.setLayout(new BoxLayout(positionPanel,
				BoxLayout.PAGE_AXIS));
		// positionPanel.setLayout(new GroupLayout(positionPanel));

		// our label
		JLabel jogLabel = new JLabel("Jog Size");
		// jogLabel.setHorizontalAlignment(JLabel.LEADING);

		// create our jog size dropdown
		JComboBox jogList = new JComboBox(jogStrings);
		// TODO: pull this from prefs
		jogList.setSelectedIndex(6);
		jogList.setMaximumSize(new Dimension(textBoxWidth, 25));
		jogList.setMinimumSize(new Dimension(textBoxWidth, 25));
		jogList.setPreferredSize(new Dimension(textBoxWidth, 25));
		jogList.setActionCommand("jog size");
		jogList.addActionListener(this);

		// our labels
		JLabel xPosLabel = new JLabel("X Position");
		// xPosLabel.setHorizontalAlignment(JLabel.LEFT);

		JLabel yPosLabel = new JLabel("Y Position");
		// yPosLabel.setHorizontalAlignment(JLabel.LEFT);

		JLabel zPosLabel = new JLabel("Z Position");
		// zPosLabel.setHorizontalAlignment(JLabel.LEFT);

		// our position text boxes
		xPosField = createDisplayField();
		yPosField = createDisplayField();
		zPosField = createDisplayField();

		// our 'go' button
		JButton goButton = new JButton("Go.");

		goButton.setToolTipText("Go to selected coordinates.");
		// goButton.setMaximumSize(new Dimension(textBoxWidth, 25));
		// goButton.setMinimumSize(new Dimension(textBoxWidth, 25));
		// goButton.setPreferredSize(new Dimension(textBoxWidth, 25));
		goButton.addActionListener(this);
		goButton.setEnabled(false);

		// add them all to position panel
		positionPanel.add(jogLabel);
		positionPanel.add(jogList);
		positionPanel.add(xPosLabel);
		positionPanel.add(xPosField);
		positionPanel.add(yPosLabel);
		positionPanel.add(yPosField);
		positionPanel.add(zPosLabel);
		positionPanel.add(zPosField);
		// positionPanel.add(goButton);

		// create our XY panel
		JPanel xyPanel = new JPanel();
		xyPanel.setLayout(new BoxLayout(xyPanel, BoxLayout.LINE_AXIS));
		xyPanel.add(xMinusButton);

		// another panel to hold the vertical stuff
		JPanel yPanel = new JPanel();
		yPanel.setLayout(new BoxLayout(yPanel, BoxLayout.PAGE_AXIS));
		yPanel.add(yPlusButton);
		yPanel.add(zeroButton);
		yPanel.add(yMinusButton);
		xyPanel.add(yPanel);

		// finally our last button.
		xyPanel.add(xPlusButton);

		// our z panel too
		JPanel zPanel = new JPanel();
		zPanel.setLayout(new BoxLayout(zPanel, BoxLayout.PAGE_AXIS));
		zPanel.add(zPlusButton);
		// zPanel.add(Box.createVerticalGlue());
		zPanel.add(zMinusButton);

		// add them both to our xyz panel
		JPanel xyzPanel = new JPanel();
		xyzPanel.setLayout(new BoxLayout(xyzPanel, BoxLayout.LINE_AXIS));
		xyzPanel.add(xyPanel);
		xyzPanel.add(Box.createHorizontalGlue());
		xyzPanel.add(zPanel);
		xyzPanel.add(Box.createHorizontalGlue());
		xyzPanel.add(positionPanel);

		// create our xy slider
		int maxXYFeedrate = (int) Math.min(machine.getModel()
				.getMaximumFeedrates().x, machine.getModel()
				.getMaximumFeedrates().y);
		int currentXYFeedrate = Math.min(maxXYFeedrate, Base.preferences
				.getInt("controlpanel.feedrate.xy",480));
		xyFeedrateSlider = new JSlider(JSlider.HORIZONTAL, 1, maxXYFeedrate,
				currentXYFeedrate);
		xyFeedrateSlider.setMajorTickSpacing(1000);
		xyFeedrateSlider.setMinorTickSpacing(100);
		xyFeedrateSlider.setName("xy-feedrate-slider");
		xyFeedrateSlider.addChangeListener(this);

		// our label
		JLabel xyFeedrateLabel = new JLabel("XY Feedrate (mm/min.)");
		xyFeedrateLabel.setVerticalAlignment(JLabel.BOTTOM);

		// our display box
		xyFeedrateValue = new JTextField();
		xyFeedrateValue.setMaximumSize(new Dimension(50, 25));
		xyFeedrateValue.setMinimumSize(new Dimension(50, 25));
		xyFeedrateValue.setPreferredSize(new Dimension(50, 25));
		xyFeedrateValue.setEnabled(true);
		xyFeedrateValue.setName("xy-feedrate-value");
		xyFeedrateValue.setText(Integer.toString(xyFeedrateSlider.getValue()));
		xyFeedrateValue.addFocusListener(this);
		xyFeedrateValue.setActionCommand("handleTextfield");
		xyFeedrateValue.addActionListener(this);

		// create the xyfeedrate panel
		JPanel xyFeedratePanel = new JPanel();
		xyFeedratePanel.setLayout(new BoxLayout(xyFeedratePanel,
				BoxLayout.LINE_AXIS));

		// add our components
		xyFeedratePanel.add(xyFeedrateLabel);
		xyFeedratePanel.add(xyFeedrateSlider);
		xyFeedratePanel.add(xyFeedrateValue);

		// create our z slider
		int maxZFeedrate = (int) machine.getModel().getMaximumFeedrates().z;
		int currentZFeedrate = Math.min(maxZFeedrate, Base.preferences
				.getInt("controlpanel.feedrate.z",480));
		zFeedrateSlider = new JSlider(JSlider.HORIZONTAL, 1, maxZFeedrate,
				currentZFeedrate);
		zFeedrateSlider.setMajorTickSpacing(10);
		zFeedrateSlider.setMinorTickSpacing(1);
		zFeedrateSlider.setName("z-feedrate-slider");
		zFeedrateSlider.addChangeListener(this);

		// our label
		JLabel zFeedrateLabel = new JLabel("Z Feedrate (mm/min.)");
		zFeedrateLabel.setVerticalAlignment(JLabel.BOTTOM);

		// our display box
		zFeedrateValue = new JTextField();
		zFeedrateValue.setMaximumSize(new Dimension(50, 25));
		zFeedrateValue.setMinimumSize(new Dimension(50, 25));
		zFeedrateValue.setPreferredSize(new Dimension(50, 25));
		zFeedrateValue.setEnabled(true);
		zFeedrateValue.setName("z-feedrate-value");
		zFeedrateValue.setText(Integer.toString(zFeedrateSlider.getValue()));
		zFeedrateValue.addFocusListener(this);
		zFeedrateValue.setActionCommand("handleTextfield");
		zFeedrateValue.addActionListener(this);

		// create the xyfeedrate panel
		JPanel zFeedratePanel = new JPanel();
		zFeedratePanel.setLayout(new BoxLayout(zFeedratePanel,
				BoxLayout.LINE_AXIS));

		// add our components
		zFeedratePanel.add(zFeedrateLabel);
		zFeedratePanel.add(zFeedrateSlider);
		zFeedratePanel.add(zFeedrateValue);

		// create our jog panel
		jogPanel = new JPanel();
		jogPanel.setLayout(new BoxLayout(jogPanel, BoxLayout.PAGE_AXIS));

		// proper size!
		// jogPanel.setMinimumSize(new Dimension(420, 300));
		// jogPanel.setMaximumSize(new Dimension(420, 300));
		// jogPanel.setPreferredSize(new Dimension(420, 300));

		// add it all to our jog panel
		jogPanel.add(xyzPanel);
		jogPanel.add(xyFeedratePanel);
		jogPanel.add(zFeedratePanel);

		// add jog panel border and stuff.
		jogPanel.setBorder(BorderFactory.createTitledBorder("Jog Controls"));

		mainPanel.add(jogPanel);
	}

	/**
	 * The activation panel contains functions related to pausing, starting, and
	 * powering the steppers up or down.
	 */
	protected void createActivationPanel() {
		JPanel activationPanel = new JPanel();
		activationPanel.setBorder(BorderFactory
				.createTitledBorder("Activation Controls"));
		activationPanel.setLayout(new BoxLayout(activationPanel,
				BoxLayout.LINE_AXIS));

		// / Enable/disable steppers.
		JButton enableButton = new JButton("Enable steppers");
		enableButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				driver.enableDrives();
			}
		});
		activationPanel.add(enableButton);
		JButton disableButton = new JButton("Disable steppers");
		disableButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				driver.disableDrives();
			}
		});
		activationPanel.add(disableButton);

		activationPanel.add(Box.createHorizontalGlue());

		mainPanel.add(activationPanel);
	}

	protected void createToolsPanel() {
		toolsPane = new JTabbedPane();

		for (Enumeration<ToolModel> e = machine.getModel().getTools().elements(); e
				.hasMoreElements();) {
			ToolModel t = e.nextElement();

			xyFeedrateValue.setText(Integer.toString(xyFeedrateSlider
					.getValue()));
			if (t.getType().equals("extruder")) {
				Base.logger.fine("Creating panel for " + t.getName());
				createExtruderPanel(t);
			} else {
				Base.logger.warning("Unsupported tool for control panel.");
			}
		}

		// add it all in. //zPanel.add(Box.createVerticalGlue());

		// JPanel toolsPanel = new JPanel();
		// toolsPanel.add(toolsPane);
		mainPanel.add(toolsPane);
	}

	protected void createExtruderPanel(ToolModel t) {
		int textBoxWidth = 75;
		Dimension labelMinimumSize = new Dimension(175, 25);
		Dimension panelSize = new Dimension(420, 30);

		// create our initial panel
		JPanel panel = new JPanel();
		BoxLayout layout = new BoxLayout(panel, BoxLayout.PAGE_AXIS);
		panel.setLayout(layout);
		// GridLayout extruderGrid = new GridLayout(0, 1);
		// panel.setLayout(extruderGrid);

		// create our motor options
		if (t.hasMotor()) {
			// Due to current implementation issues, we need to send the PWM
			// before the RPM
			// for a stepper motor. Thus we display both controls in these
			// cases.
			{
				// our motor speed vars
				JLabel label = new JLabel();
				JTextField field = new JTextField();
				label.setText("Motor Speed (PWM)");
				label.setMinimumSize(labelMinimumSize);
				label.setMaximumSize(labelMinimumSize);
				label.setPreferredSize(labelMinimumSize);
				label.setHorizontalAlignment(JLabel.LEFT);

				field.setMaximumSize(new Dimension(textBoxWidth, 25));
				field.setMinimumSize(new Dimension(textBoxWidth, 25));
				field.setPreferredSize(new Dimension(textBoxWidth, 25));
				field.setName("motor-speed-pwm");
				field.addFocusListener(this);
				field.setActionCommand("handleTextfield");
				field.addActionListener(this);

				JPanel motorSpeedPanel = new JPanel();
				motorSpeedPanel.setLayout(new BoxLayout(motorSpeedPanel,
						BoxLayout.LINE_AXIS));
				motorSpeedPanel.setMaximumSize(panelSize);
				motorSpeedPanel.setMinimumSize(panelSize);
				motorSpeedPanel.setPreferredSize(panelSize);
				motorSpeedPanel.add(label);
				motorSpeedPanel.add(field);
				panel.add(motorSpeedPanel);
			}

			if (t.motorHasEncoder() || t.motorIsStepper()) {
				JLabel label = new JLabel();
				JTextField field = new JTextField();
				// our motor speed vars
				label.setText("Motor Speed (RPM)");
				label.setMinimumSize(labelMinimumSize);
				label.setMaximumSize(labelMinimumSize);
				label.setPreferredSize(labelMinimumSize);
				label.setHorizontalAlignment(JLabel.LEFT);

				field.setMaximumSize(new Dimension(textBoxWidth, 25));
				field.setMinimumSize(new Dimension(textBoxWidth, 25));
				field.setPreferredSize(new Dimension(textBoxWidth, 25));
				field.setName("motor-speed");
				field.addFocusListener(this);
				field.setActionCommand("handleTextfield");
				field.addActionListener(this);

				JPanel motorSpeedPanel = new JPanel();
				motorSpeedPanel.setLayout(new BoxLayout(motorSpeedPanel,
						BoxLayout.LINE_AXIS));
				motorSpeedPanel.setMaximumSize(panelSize);
				motorSpeedPanel.setMinimumSize(panelSize);
				motorSpeedPanel.setPreferredSize(panelSize);
				motorSpeedPanel.add(label);
				motorSpeedPanel.add(field);
				panel.add(motorSpeedPanel);
			}
			// create our motor options
			JLabel motorEnabledLabel = new JLabel("Motor Control");
			motorEnabledLabel.setMinimumSize(labelMinimumSize);
			motorEnabledLabel.setMaximumSize(labelMinimumSize);
			motorEnabledLabel.setPreferredSize(labelMinimumSize);
			motorEnabledLabel.setHorizontalAlignment(JLabel.LEFT);

			JRadioButton motorReverseButton = new JRadioButton("reverse");
			motorReverseButton.setName("motor-reverse");
			motorReverseButton.addItemListener(this);

			JRadioButton motorStoppedButton = new JRadioButton("stop");
			motorStoppedButton.setName("motor-stop");
			motorStoppedButton.addItemListener(this);

			JRadioButton motorForwardButton = new JRadioButton("forward");
			motorForwardButton.setName("motor-forward");
			motorForwardButton.addItemListener(this);

			ButtonGroup motorControl = new ButtonGroup();
			motorControl.add(motorReverseButton);
			motorControl.add(motorStoppedButton);
			motorControl.add(motorForwardButton);

			JPanel motorControlPanel = new JPanel();
			motorControlPanel.setLayout(new BoxLayout(motorControlPanel,
					BoxLayout.LINE_AXIS));
			motorControlPanel.setMaximumSize(panelSize);
			motorControlPanel.setMinimumSize(panelSize);
			motorControlPanel.setPreferredSize(panelSize);

			// add components in.
			motorControlPanel.add(motorEnabledLabel);
			motorControlPanel.add(motorReverseButton);
			motorControlPanel.add(motorStoppedButton);
			motorControlPanel.add(motorForwardButton);
			panel.add(motorControlPanel);
		}

		// our temperature fields
		if (t.hasHeater()) {
			JLabel targetTempLabel = new JLabel("Target Temperature (C)");
			targetTempLabel.setMinimumSize(labelMinimumSize);
			targetTempLabel.setMaximumSize(labelMinimumSize);
			targetTempLabel.setPreferredSize(labelMinimumSize);
			targetTempLabel.setHorizontalAlignment(JLabel.LEFT);

			JTextField targetTempField = new JTextField();
			targetTempField.setMaximumSize(new Dimension(textBoxWidth, 25));
			targetTempField.setMinimumSize(new Dimension(textBoxWidth, 25));
			targetTempField.setPreferredSize(new Dimension(textBoxWidth, 25));
			targetTempField.setName("target-temp");
			targetTempField.addFocusListener(this);
			double temperature = driver.getMachine().currentTool().getTargetTemperature();
			targetTempField.setText(Double.toString(temperature));
			targetTempField.setActionCommand("handleTextfield");
			targetTempField.addActionListener(this);

			JLabel currentTempLabel = new JLabel("Current Temperature (C)");
			currentTempLabel.setMinimumSize(labelMinimumSize);
			currentTempLabel.setMaximumSize(labelMinimumSize);
			currentTempLabel.setPreferredSize(labelMinimumSize);
			currentTempLabel.setHorizontalAlignment(JLabel.LEFT);

			currentTempField = new JTextField();
			currentTempField.setMaximumSize(new Dimension(textBoxWidth, 25));
			currentTempField.setMinimumSize(new Dimension(textBoxWidth, 25));
			currentTempField.setPreferredSize(new Dimension(textBoxWidth, 25));
			currentTempField.setEnabled(false);

			JPanel targetTempPanel = new JPanel();
			targetTempPanel.setLayout(new BoxLayout(targetTempPanel,
					BoxLayout.LINE_AXIS));
			targetTempPanel.setMaximumSize(panelSize);
			targetTempPanel.setMinimumSize(panelSize);
			targetTempPanel.setPreferredSize(panelSize);

			JPanel currentTempPanel = new JPanel();
			currentTempPanel.setLayout(new BoxLayout(currentTempPanel,
					BoxLayout.LINE_AXIS));
			currentTempPanel.setMaximumSize(panelSize);
			currentTempPanel.setMinimumSize(panelSize);
			currentTempPanel.setPreferredSize(panelSize);

			targetTempPanel.add(targetTempLabel);
			targetTempPanel.add(targetTempField);
			panel.add(targetTempPanel);
			currentTempPanel.add(currentTempLabel);
			currentTempPanel.add(currentTempField);
			panel.add(currentTempPanel);
		}

		// our heated platform fields
		if (t.hasHeatedPlatform()) {
			JLabel targetTempLabel = new JLabel("Platform Target Temp (C)");
			targetTempLabel.setMinimumSize(labelMinimumSize);
			targetTempLabel.setMaximumSize(labelMinimumSize);
			targetTempLabel.setPreferredSize(labelMinimumSize);
			targetTempLabel.setHorizontalAlignment(JLabel.LEFT);

			JTextField targetTempField = new JTextField();
			targetTempField.setMaximumSize(new Dimension(textBoxWidth, 25));
			targetTempField.setMinimumSize(new Dimension(textBoxWidth, 25));
			targetTempField.setPreferredSize(new Dimension(textBoxWidth, 25));
			targetTempField.setName("platform-target-temp");
			targetTempField.addFocusListener(this);
			double temperature = driver.getMachine().currentTool().getPlatformTargetTemperature();
			targetTempField.setText(Double.toString(temperature));
			targetTempField.setActionCommand("handleTextfield");
			targetTempField.addActionListener(this);

			JLabel currentTempLabel = new JLabel("Platform Current Temp (C)");
			currentTempLabel.setMinimumSize(labelMinimumSize);
			currentTempLabel.setMaximumSize(labelMinimumSize);
			currentTempLabel.setPreferredSize(labelMinimumSize);
			currentTempLabel.setHorizontalAlignment(JLabel.LEFT);

			platformCurrentTempField = new JTextField();
			platformCurrentTempField.setMaximumSize(new Dimension(textBoxWidth, 25));
			platformCurrentTempField.setMinimumSize(new Dimension(textBoxWidth, 25));
			platformCurrentTempField.setPreferredSize(new Dimension(textBoxWidth, 25));
			platformCurrentTempField.setEnabled(false);

			JPanel targetTempPanel = new JPanel();
			targetTempPanel.setLayout(new BoxLayout(targetTempPanel,
					BoxLayout.LINE_AXIS));
			targetTempPanel.setMaximumSize(panelSize);
			targetTempPanel.setMinimumSize(panelSize);
			targetTempPanel.setPreferredSize(panelSize);

			JPanel currentTempPanel = new JPanel();
			currentTempPanel.setLayout(new BoxLayout(currentTempPanel,
					BoxLayout.LINE_AXIS));
			currentTempPanel.setMaximumSize(panelSize);
			currentTempPanel.setMinimumSize(panelSize);
			currentTempPanel.setPreferredSize(panelSize);

			targetTempPanel.add(targetTempLabel);
			targetTempPanel.add(targetTempField);
			panel.add(targetTempPanel);
			currentTempPanel.add(currentTempLabel);
			currentTempPanel.add(platformCurrentTempField);
			panel.add(currentTempPanel);
		}

		// flood coolant controls
		if (t.hasFloodCoolant()) {
			JLabel floodCoolantLabel = new JLabel("Flood Coolant");
			floodCoolantLabel.setMinimumSize(labelMinimumSize);
			floodCoolantLabel.setMaximumSize(labelMinimumSize);
			floodCoolantLabel.setPreferredSize(labelMinimumSize);
			floodCoolantLabel.setHorizontalAlignment(JLabel.LEFT);

			JCheckBox floodCoolantCheck = new JCheckBox("enable");
			floodCoolantCheck.setName("flood-coolant");
			floodCoolantCheck.addItemListener(this);

			JPanel floodCoolantPanel = new JPanel();
			floodCoolantPanel.setLayout(new BoxLayout(floodCoolantPanel,
					BoxLayout.LINE_AXIS));
			floodCoolantPanel.setMaximumSize(panelSize);
			floodCoolantPanel.setMinimumSize(panelSize);
			floodCoolantPanel.setPreferredSize(panelSize);

			floodCoolantPanel.add(floodCoolantLabel);
			floodCoolantPanel.add(floodCoolantCheck);
			panel.add(floodCoolantPanel);
		}

		// mist coolant controls
		if (t.hasMistCoolant()) {
			JLabel mistCoolantLabel = new JLabel("Mist Coolant");
			mistCoolantLabel.setMinimumSize(labelMinimumSize);
			mistCoolantLabel.setMaximumSize(labelMinimumSize);
			mistCoolantLabel.setPreferredSize(labelMinimumSize);
			mistCoolantLabel.setHorizontalAlignment(JLabel.LEFT);

			JCheckBox mistCoolantCheck = new JCheckBox("enable");
			mistCoolantCheck.setName("mist-coolant");
			mistCoolantCheck.addItemListener(this);

			JPanel mistCoolantPanel = new JPanel();
			mistCoolantPanel.setLayout(new BoxLayout(mistCoolantPanel,
					BoxLayout.LINE_AXIS));
			mistCoolantPanel.setMaximumSize(panelSize);
			mistCoolantPanel.setMinimumSize(panelSize);
			mistCoolantPanel.setPreferredSize(panelSize);

			mistCoolantPanel.add(mistCoolantLabel);
			mistCoolantPanel.add(mistCoolantCheck);
			panel.add(mistCoolantPanel);
		}

		// cooling fan controls
		if (t.hasFan()) {
			String fanString = "Cooling Fan";
			String enableString = "enable";
			Element xml = findMappingNode(t.getXml(),"fan");
			if (xml != null) {
				fanString = xml.getAttribute("name");
				enableString = xml.getAttribute("actuated");
			}
			JLabel fanLabel = new JLabel(fanString);
			fanLabel.setMinimumSize(labelMinimumSize);
			fanLabel.setMaximumSize(labelMinimumSize);
			fanLabel.setPreferredSize(labelMinimumSize);
			fanLabel.setHorizontalAlignment(JLabel.LEFT);

			JCheckBox fanCheck = new JCheckBox(enableString);
			fanCheck.setName("fan-check");
			fanCheck.addItemListener(this);

			JPanel fanPanel = new JPanel();
			fanPanel.setLayout(new BoxLayout(fanPanel, BoxLayout.LINE_AXIS));
			fanPanel.setMaximumSize(panelSize);
			fanPanel.setMinimumSize(panelSize);
			fanPanel.setPreferredSize(panelSize);

			fanPanel.add(fanLabel);
			fanPanel.add(fanCheck);
			panel.add(fanPanel);
		}

		// valve controls
		if (t.hasValve()) {
			String valveString = "Valve";
			String enableString = "open";

			Element xml = findMappingNode(t.getXml(),"valve");
			if (xml != null) {
				valveString = xml.getAttribute("name");
				enableString = xml.getAttribute("actuated");
			}
			
			JLabel valveLabel = new JLabel(valveString);
			valveLabel.setMinimumSize(labelMinimumSize);
			valveLabel.setMaximumSize(labelMinimumSize);
			valveLabel.setPreferredSize(labelMinimumSize);
			valveLabel.setHorizontalAlignment(JLabel.LEFT);

			JCheckBox valveCheck = new JCheckBox(enableString);
			valveCheck.setName("valve-check");
			valveCheck.addItemListener(this);

			JPanel valvePanel = new JPanel();
			valvePanel
					.setLayout(new BoxLayout(valvePanel, BoxLayout.LINE_AXIS));
			valvePanel.setMaximumSize(panelSize);
			valvePanel.setMinimumSize(panelSize);
			valvePanel.setPreferredSize(panelSize);

			valvePanel.add(valveLabel);
			valvePanel.add(valveCheck);
			panel.add(valvePanel);
		}

		// valve controls
		if (t.hasCollet()) {
			JLabel colletLabel = new JLabel("Collet");
			colletLabel.setMinimumSize(labelMinimumSize);
			colletLabel.setMaximumSize(labelMinimumSize);
			colletLabel.setPreferredSize(labelMinimumSize);
			colletLabel.setHorizontalAlignment(JLabel.LEFT);

			JCheckBox colletCheck = new JCheckBox("open");
			colletCheck.setName("collet-check");
			colletCheck.addItemListener(this);

			JPanel colletPanel = new JPanel();
			colletPanel.setLayout(new BoxLayout(colletPanel,
					BoxLayout.LINE_AXIS));
			colletPanel.setMaximumSize(panelSize);
			colletPanel.setMinimumSize(panelSize);
			colletPanel.setPreferredSize(panelSize);

			colletPanel.add(colletLabel);
			colletPanel.add(colletCheck);
			panel.add(colletPanel);
		}
		toolsPane.addTab(t.getName(), panel);
	}

	private Element findMappingNode(Node xml,String portName) {
		// scan the remapping nodes.
		NodeList children = xml.getChildNodes();
		for (int j=0; j<children.getLength(); j++) {
			Node child = children.item(j);
			if (child.getNodeName().equals("remap")) {
				Element e = (Element)child;
				if (e.getAttribute("port").equals(portName)) {
					return e;
				}
			}
		}
		return null;
	}
	
	DecimalFormat positionFormatter = new DecimalFormat("###.#");

	synchronized public void updateStatus() {
		Point3d current = driver.getCurrentPosition();

		xPosField.setText(positionFormatter.format(current.x));
		yPosField.setText(positionFormatter.format(current.y));
		zPosField.setText(positionFormatter.format(current.z));
		
		if (driver.getMachine().currentTool() != null &&
			driver.getMachine().currentTool().hasHeater()) {
			double temperature = driver.getTemperature();
			currentTempField.setText(Double.toString(temperature));
		}
		if (driver.getMachine().currentTool() != null &&
			driver.getMachine().currentTool().hasHeatedPlatform()) {
			double temperature = driver.getPlatformTemperature();
			platformCurrentTempField.setText(Double.toString(temperature));
		}
	}

	public void actionPerformed(ActionEvent e) {
		String s = e.getActionCommand();
		
		if(s.equals("handleTextfield"))
		{
			JTextField source = (JTextField) e.getSource();
			handleChangedTextField(source);
			source.selectAll();
		}
		else
		{
			Point3d current = driver.getCurrentPosition();
			double xyFeedrate = xyFeedrateSlider.getValue();
			double zFeedrate = zFeedrateSlider.getValue();
	
			if (s.equals("X+")) {
				current.x += jogRate;
	
				driver.setFeedrate(xyFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("X-")) {
				current.x -= jogRate;
	
				driver.setFeedrate(xyFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("Y+")) {
				current.y += jogRate;
	
				driver.setFeedrate(xyFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("Y-")) {
				current.y -= jogRate;
	
				driver.setFeedrate(xyFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("Z+")) {
				current.z += jogRate;
	
				driver.setFeedrate(zFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("Z-")) {
				current.z -= jogRate;
	
				driver.setFeedrate(zFeedrate);
				driver.queuePoint(current);
			} else if (s.equals("Zero")) {
				// "Zero" tells the machine to calibrate its
				// current position as zero, not to move to its
				// currently-set zero position.
				driver.setCurrentPosition(new Point3d());
			}
			// get our new jog rate
			else if (s.equals("jog size")) {
				JComboBox cb = (JComboBox) e.getSource();
				String jogText = (String) cb.getSelectedItem();
	
				// look for a decimal number
				Matcher jogMatcher = jogPattern.matcher(jogText);
				if (jogMatcher.find())
					jogRate = Double.parseDouble(jogMatcher.group(1));
	
				// TODO: save this back to our preferences file.
	
				// System.out.println("jog rate: " + jogRate);
			} else
				Base.logger.warning("Unknown Action Event: " + s);
		}
	}

	public void stateChanged(ChangeEvent e) {
		JSlider source = (JSlider) e.getSource();
		int feedrate = source.getValue();

		if (source.getName().equals("xy-feedrate-slider")) {
			xyFeedrateValue.setText(Integer.toString(feedrate));
		} else if (source.getName().equals("z-feedrate-slider")) {
			zFeedrateValue.setText(Integer.toString(feedrate));
		}
	}

	public void itemStateChanged(ItemEvent e) {
		Component source = (Component) e.getItemSelectable();
		String name = source.getName();

		if (e.getStateChange() == ItemEvent.SELECTED) {
			if (name.equals("motor-forward")) {
				driver.setMotorDirection(ToolModel.MOTOR_CLOCKWISE);
				driver.enableMotor();
			} else if (name.equals("motor-reverse")) {
				driver.setMotorDirection(ToolModel.MOTOR_COUNTER_CLOCKWISE);
				driver.enableMotor();
			} else if (name.equals("motor-stop"))
				driver.disableMotor();
			else if (name.equals("spindle-enabled"))
				driver.enableSpindle();
			else if (name.equals("flood-coolant"))
				driver.enableFloodCoolant();
			else if (name.equals("mist-coolant"))
				driver.enableMistCoolant();
			else if (name.equals("fan-check"))
				driver.enableFan();
			else if (name.equals("valve-check"))
				driver.openValve();
			else if (name.equals("collet-check"))
				driver.openCollet();
			else
				Base.logger.warning("checkbox selected: " + source.getName());
		} else {
			if (name.equals("motor-enabled"))
				driver.disableMotor();
			else if (name.equals("spindle-enabled"))
				driver.disableSpindle();
			else if (name.equals("flood-coolant"))
				driver.disableFloodCoolant();
			else if (name.equals("mist-coolant"))
				driver.disableMistCoolant();
			else if (name.equals("fan-check"))
				driver.disableFan();
			else if (name.equals("valve-check"))
				driver.closeValve();
			else if (name.equals("collet-check"))
				driver.closeCollet();
			// else
			// System.out.println("checkbox deselected: " + source.getName());
		}
	}

	public void focusGained(FocusEvent e) {
	}

	public void focusLost(FocusEvent e) {
		JTextField source = (JTextField) e.getSource();
		handleChangedTextField(source);
	}

	public void handleChangedTextField(JTextField source)
	{
		String name = source.getName();

		if (source.getText().length() > 0) {
			if (name.equals("target-temp")) {
				driver.setTemperature(Double.parseDouble(source.getText()));
			} else if (name.equals("platform-target-temp")) {
				driver.setPlatformTemperature(Double.parseDouble(source.getText()));
			} else if (name.equals("motor-speed")) {
				driver.setMotorRPM(Double.parseDouble(source.getText()));
			} else if (name.equals("motor-speed-pwm")) {
				driver.setMotorSpeedPWM(Integer.parseInt(source.getText()));
			} else if (name.equals("xy-feedrate-value")) {
				xyFeedrateSlider.setValue(Integer.parseInt(source.getText()));
			} else if (name.equals("z-feedrate-value")) {
				zFeedrateSlider.setValue(Integer.parseInt(source.getText()));
			} else
				Base.logger.warning("Unhandled text field: "+name);
		}
	}
	
	public void windowClosing(WindowEvent e) {
		updateThread.interrupt();
		pollThread.interrupt();
	}

	public void windowClosed(WindowEvent e) {
		synchronized(getClass()) {
			machine.removeMachineStateListener(this);
			if (instance == this) {
				instance = null;
			}
		}
	}

	public void windowOpened(WindowEvent e) {
	}

	public void windowIconified(WindowEvent e) {
	}

	public void windowDeiconified(WindowEvent e) {
	}

	public void windowActivated(WindowEvent e) {
	}

	public void windowDeactivated(WindowEvent e) {
	}

	class PollThread extends Thread {
		Driver driver;

		public PollThread(Driver d) {
			super("Control Panel Poll Thread");

			driver = d;
		}

		public void run() {
			// we'll break on interrupts
			try {
				while (true) {
					// driver.readTemperature();
					Thread.sleep(1000);
				}
			} catch (InterruptedException e) {
			}
		}
	}

	class UpdateThread extends Thread {
		ControlPanelWindow window;

		public UpdateThread(ControlPanelWindow w) {
			super("Control Panel Update Thread");

			window = w;
		}

		public void run() {
			// we'll break on interrupts
			try {
				while (true) {
					window.updateStatus();
					Thread.sleep(1000);
				}
			} catch (InterruptedException e) {
			}
		}
	}

	public void machineProgress(MachineProgressEvent event) {
	}

	public void machineStateChanged(MachineStateChangeEvent evt) {
		if (evt.getState().isBuilding() || !evt.getState().isConnected()) {
			if (updateThread != null) { updateThread.interrupt(); }
			if (pollThread != null) { pollThread.interrupt(); }
			dispose();
		}
	}

	public void toolStatusChanged(MachineToolStatusEvent event) {
	}
}
