(**** The Replicator Utility ****)
( Change filament in extruder T0 )

M70 P5 (Heating for            filament release)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 R3.0 T0 (set extruder speed left)
M103 T0 (Make sure extruder is off)

M73 P0 (enable build progress 'Change Filament')
M104 S225 T0 (set extruder temperature)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)

M70 P90(  Ejecting Filament                       Grasp Filament closeto input and pull)
M102 T0 (Extruder on, reverse)
G04 P90000 (Wait t/1000 seconds)
M71 P200 ( Remove old Filament Load new Filament   Press M to Continue )
M101 T0 (Extruder on, forward)
M70 P120(  Loading Filament                        Grasp Filament closeto input and push)
G04 P120000 (Wait t/1000 seconds)

M103 T0 (Extruder off)
(**** begin cool for safety ****)
M104 S0 T0 (set extruder temperature)
M71 (   Loading Script         Complete )
M73 P100 (build end notification)
(**** end cool for safety ****)
(**** end of end.gcode ****)
