(**** TOM Utility - Extrude for 120s ****)
(**** beginning of start.gcode ****)
(This file is for a MakerBot Thing-O-Matic)
(**** begin initialization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 R3.0 (set extruder speed)
M103 (Make sure extruder is off)
M104 S225 T0 (set extruder temperature)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)
M102 (Extruder on, reverse)
G04 P120000 (Wait t/1000 seconds)
M103 (Extruder off)
(**** begin cool for safety ****)
M104 S0 T0 (set extruder temperature)
(**** end cool for safety ****)
(**** end of end.gcode ****)